#!/bin/bash
set -eu

source ~/bin/notify_replace

function notify() {
    notify_replace -u low "$@"
}

case "${1:-}" in
    toggle)
        pamixer --toggle-mute
        if [ "$(pamixer --get-mute)" == "true" ]; then
            notify -i "audio-volume-muted" "Muted"
        else
            notify -i "audio-volume-medium" "Unmuted" "$(pamixer --get-volume)"
        fi
        ;;
    raise)
        pamixer --unmute --increase 5
        notify -i "audio-volume-medium" "$(pamixer --get-volume)"
        ;;
    lower)
        pamixer --unmute --decrease 5
        notify -i "audio-volume-medium" "$(pamixer --get-volume)"
        ;;
    next)
        dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify \
            /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
        ;;
    prev)
        dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify \
            /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
        ;;
esac


