#!/bin/sh
export DISPLAY=":0"

critical_0=10
warning_0=25
warning_1=10

tmpDir="/tmp/battery-guard-nagbar"
mkdir -p "$tmpDir"

function nagbar() {
    type="$1"
    number="$2"
    message="$3"
    state="$tmpDir/${type}_${number}"

    if [ "$message" == "clear" ]; then
        rm -f $state
    elif [ ! -f $state ]; then
        touch $state
        i3-nagbar -m "$message" -t $type -f "pango:DejaVu Sans Mono 10" 2>&1 1> /dev/null &
    fi
}

acpi -b | awk -F'[,:%]' '{print $2, $3}' | {
    read -r status_0 capacity_0
    read -r status_1 capacity_1

    if [ "$status_1" = Discharging -a "$capacity_1" -lt $warning_1 ]; then
        nagbar warning 1 "External battery getting low ($capacity_1)"
    else
        nagbar warning 1 clear
    fi

    if [ "$status_0" = Discharging -a "$capacity_0" -lt $warning_0 ]; then
        nagbar warning 0 "Internal battery criticaly low ($capacity_0)"
    else
        nagbar warning 0 clear
    fi

    if [ "$status_0" = Discharging -a "$capacity_0" -lt $critical_0 ]; then
        logger "Critical battery threshold ($critical_0)"
        nagbar error 1 "Internal battery critically low ($capacity_0)"
        systemctl hibernate
    else
        nagbar error 1 clear
    fi
}
