#!/bin/sh
exec cpulimit -i -l 100 firejail --name=facebook \
    --nice=15 \
    --private=firejail-home/chromium-facebook \
    /usr/bin/chromium --disable-internal-flash --disable-plugins-discovery
