#!/bin/bash

defaultProfile="one"
internalMonitor="eDP1"
externalMonitor="HDMI1"

function monitorIsEnabled() {
    if [[ -n "$(xrandr | grep "$1" | grep "+")" ]]; then
        return 0
    else
        return 1
    fi
}

function monitorIsConnected() {
    if [[ -n "$(xrandr | grep "$1" | grep " connected")" ]]; then
        return 0
    else
        return 1
    fi
}

function toggleMonitors() {
    profile="$1"

    # left-of, right-of, above, below, same-as
    position="${3:-"above"}"

    if [ -n "$2" ]; then
        toggle="$2"
    elif monitorIsConnected "$externalMonitor"; then
        if monitorIsEnabled "$internalMonitor"; then
            toggle="on"
        else
            toggle="off"
        fi
    else
        toggle="off"
    fi

    if [ "$toggle" == "on" ]; then
        case "$profile" in
            "one")
                xrandr --output $internalMonitor --off \
                    --output $externalMonitor --auto #--scale 0.8x0.8
                ;;

            "two")
                xrandr --output "$internalMonitor" --off \
                    --output "$externalMonitor" --auto
                xrandr --output "$internalMonitor" --auto \
                    --output "$externalMonitor" --$position "$internalMonitor"
                ;;
        esac
    else
        xrandr --output $externalMonitor --off \
            --output $internalMonitor --auto
    fi

    if [ -n "$(ps -A | grep i3)" ]; then
        i3-msg restart
    fi

    nitrogen --restore
}

toggleMonitors ${1:-$defaultProfile} $2 $3
