#!/bin/bash

source ~/bin/notify_replace

round() {
    echo "($1+0.5)/1" | bc
}

getValue() {
    round $(xbacklight -get)
}

op="${1:-"get"}"
v="$(getValue)"

if [[ $op =~ (inc|dec) ]]; then
    if [ $v -gt 20 ]; then
        step=10
    elif [ $v -gt 5 ]; then
        step=5
    else
        step=1
    fi

    xbacklight -$op $step
    v="$(getValue)" # get new value
    notify_replace -u low -i video-display "$v%"
else
    echo $v
fi
