#!/bin/bash

internalMonitor="eDP1"
externalMonitor="HDMI1"
externalPosition="above"

function monitorIsEnabled() {
    [[ -n "$(xrandr | grep "$1" | grep "+")" ]]
}

function monitorIsConnected() {
    [[ -n "$(xrandr | grep "$1" | grep " connected")" ]]
}

function requireMonitor() {
    if ! monitorIsConnected "$1"; then
        echo "Monitor $1 is not connected"
        return 1;
    fi
}

function enableProfile() {
    profile=${1:-"default"}

    # Values: left-of, right-of, above, below or same-as
    position="${2:-"$externalPosition"}"

    case "$profile" in
        one)
            if requireMonitor $externalMonitor; then
                xrandr --output $internalMonitor --off \
                    --output $externalMonitor --auto #--scale 0.8x0.8
            fi
            ;;

        two)
            if requireMonitor $externalMonitor; then
                xrandr --output "$internalMonitor" --off \
                    --output "$externalMonitor" --auto
                xrandr --output "$internalMonitor" --auto \
                    --output "$externalMonitor" --$position "$internalMonitor" --auto
            fi
            ;;

        default|*) # and fallback
            xrandr --output $externalMonitor --off \
                --output $internalMonitor --auto
            ;;
    esac

    # this was needed to fix i3 bug, maybe no longer needed
#    if [ -n "$(ps -A | grep i3)" ]; then
#        i3-msg restart
#    fi

    nitrogen --restore # re-adjust wallpaper
}

function detectCurrentProfile() {
    currentProfile="none"

    if monitorIsConnected "$externalMonitor" && monitorIsEnabled "$externalMonitor"; then
        currentProfile="one"
    fi

    if monitorIsEnabled "$internalMonitor"; then
        if [ "$currentProfile" == "none" ]; then
            currentProfile="default"
        else
            currentProfile="two"
        fi
    fi

    echo $currentProfile
}

function toggleMonitors() {
    profile="$1"
    currentProfile="$(detectCurrentProfile)"
    echo "current profile $currentProfile"

    if [[ "$currentProfile" =~ ^($profile|none)$ ]]; then
        profile="default"
    fi

    echo "enable profile $profile"
    enableProfile $profile $2
}

function hotplugMonitors() {
    currentProfile="$(detectCurrentProfile)"

    if monitorIsConnected "$externalMonitor"; then
        if [ "$currentProfile" == "default" ]; then
            if which i3-nagbar; then
                i3-nagbar -m "External monitor connected" -t warning \
                    -b "ONE: Use only external monitor" "$0 one" \
                    -b "TWO: Use both internal and external monitors" "$0 two" \
                    -b "DEFAULT: Use only internal monitor" "$0 default" ;
            else
                enableProfile one
            fi
        fi
    elif [ "$currentProfile" != "default" ]; then
        enableProfile default
    fi
}

profile=${1:-"one"}

if [ "$profile" == "hotplug" ]; then
    while true; do
        hotplugMonitors
        sleep 5
    done
else
    toggleMonitors $profile $2
fi

