#!/bin/bash

internalMonitor="eDP1"
externalMonitor="HDMI1"

function monitorIsEnabled() {
    if [[ -n "$(xrandr | grep "$1" | grep "+")" ]]; then
        return 0
    else
        return 1
    fi
}

function monitorIsConnected() {
    if [[ -n "$(xrandr | grep "$1" | grep " connected")" ]]; then
        return 0
    else
        return 1
    fi
}

state="init"

function detectMonitors() {
    # left-of, right-of, above, below, same-as
    position="${2:-"above"}"

    if monitorIsConnected "$externalMonitor"; then
        if monitorIsEnabled "$internalMonitor"; then
            toggle="on"
        else
            #toggle="off"
            return 0 # external connected and internal disabled
        fi
    else
        toggle="off"
    fi

    echo "$toggle != $state"
    if [ "$state" != "init" -a "$state" == "$toggle" ]; then
        echo "Nothing to do"
        return 0 # Nothing new to do
    fi

    if [ "$toggle" == "on" ]; then
        state="on"

        echo "ON"
        i3-nagbar -m "External display connected" -t warning \
            -b "Use ONLY external display" "/home/atmoz/bin/monitor-toggle one on" \
            -b "Use both internal and external display" "/home/atmoz/bin/monitor-toggle two on"
        sleep 3
    else
        state="off"
        echo "OFF"
        /home/atmoz/bin/monitor-toggle one off
    fi
}

while true; do
    detectMonitors
    echo "Sleeping ..."
    sleep 2
done
