#!/bin/bash
# Because transmission is running in firejail, we need to move the torrent file
# to /tmp. This script makes this easier.

file="$(ls ~/.firejail-home/chromium/*/Downloads/*.torrent | dmenu)"
if [ ! -f "$file" ]; then
    echo "No file selected, nothing is done."
    exit 0
fi

tmpFile="/tmp/$(basename "$file")"
mv "$file" "$tmpFile"
( transmission-gtk "$tmpFile" 2>&1 > /dev/null & )

