#!/bin/bash
set -e

dev=/dev/sdb1
mapper=/dev/mapper/luks-35f8cae8-4ca6-4463-bb10-21cd85651615

udisksctl unlock -b $dev
udisksctl mount -b $mapper
rsync -av --stats /home/atmoz/Dropbox/ /run/media/atmoz/e1cbc2a4-3e7a-49c8-b23c-78f4162f6295/Dropbox
sleep 2
udisksctl unmount -b $mapper
udisksctl lock -b $dev
