#!/bin/bash

# Make 80 column text fit perfectly
read -r -d '' header << 'EOS'
---
geometry: margin=2.25cm
fontsize: 12pt
---
\pagenumbering{gobble}
```
EOS

read -r -d '' footer << 'EOS'
```
EOS

# Feed it all to pandoc (echo madness for consistent linebreaks)
echo "$(echo "$header"; echo "$(cat "$1")"; echo "$footer")" | pandoc -o "$1.pdf" -
