#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

jar=$DIR/src/google-java-format/google-java-format-1.3-all-deps.jar

if [ ! -f "$jar" ]; then
    echo "Could not find jar: $jar" >&2
    exit 1
fi

java -jar $jar $@

